/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SedeRouteImport } from './routes/sede'
import { Route as ProgramaRouteImport } from './routes/programa'
import { Route as InvitadosRouteImport } from './routes/invitados'
import { Route as InscripcionesRouteImport } from './routes/inscripciones'
import { Route as InformacionRouteImport } from './routes/informacion'
import { Route as BienvenidosRouteImport } from './routes/bienvenidos'
import { Route as AutoridadesRouteImport } from './routes/autoridades'
import { Route as AlojamientoRouteImport } from './routes/alojamiento'
import { Route as IndexRouteImport } from './routes/index'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SedeRoute = SedeRouteImport.update({
  id: '/sede',
  path: '/sede',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaRoute = ProgramaRouteImport.update({
  id: '/programa',
  path: '/programa',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitadosRoute = InvitadosRouteImport.update({
  id: '/invitados',
  path: '/invitados',
  getParentRoute: () => rootRouteImport,
} as any)
const InscripcionesRoute = InscripcionesRouteImport.update({
  id: '/inscripciones',
  path: '/inscripciones',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacionRoute = InformacionRouteImport.update({
  id: '/informacion',
  path: '/informacion',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidosRoute = BienvenidosRouteImport.update({
  id: '/bienvenidos',
  path: '/bienvenidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoridadesRoute = AutoridadesRouteImport.update({
  id: '/autoridades',
  path: '/autoridades',
  getParentRoute: () => rootRouteImport,
} as any)
const AlojamientoRoute = AlojamientoRouteImport.update({
  id: '/alojamiento',
  path: '/alojamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alojamiento': typeof AlojamientoRoute
  '/autoridades': typeof AutoridadesRoute
  '/bienvenidos': typeof BienvenidosRoute
  '/informacion': typeof InformacionRoute
  '/inscripciones': typeof InscripcionesRoute
  '/invitados': typeof InvitadosRoute
  '/programa': typeof ProgramaRoute
  '/sede': typeof SedeRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alojamiento': typeof AlojamientoRoute
  '/autoridades': typeof AutoridadesRoute
  '/bienvenidos': typeof BienvenidosRoute
  '/informacion': typeof InformacionRoute
  '/inscripciones': typeof InscripcionesRoute
  '/invitados': typeof InvitadosRoute
  '/programa': typeof ProgramaRoute
  '/sede': typeof SedeRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alojamiento': typeof AlojamientoRoute
  '/autoridades': typeof AutoridadesRoute
  '/bienvenidos': typeof BienvenidosRoute
  '/informacion': typeof InformacionRoute
  '/inscripciones': typeof InscripcionesRoute
  '/invitados': typeof InvitadosRoute
  '/programa': typeof ProgramaRoute
  '/sede': typeof SedeRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alojamiento'
    | '/autoridades'
    | '/bienvenidos'
    | '/informacion'
    | '/inscripciones'
    | '/invitados'
    | '/programa'
    | '/sede'
    | '/sponsors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alojamiento'
    | '/autoridades'
    | '/bienvenidos'
    | '/informacion'
    | '/inscripciones'
    | '/invitados'
    | '/programa'
    | '/sede'
    | '/sponsors'
  id:
    | '__root__'
    | '/'
    | '/alojamiento'
    | '/autoridades'
    | '/bienvenidos'
    | '/informacion'
    | '/inscripciones'
    | '/invitados'
    | '/programa'
    | '/sede'
    | '/sponsors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlojamientoRoute: typeof AlojamientoRoute
  AutoridadesRoute: typeof AutoridadesRoute
  BienvenidosRoute: typeof BienvenidosRoute
  InformacionRoute: typeof InformacionRoute
  InscripcionesRoute: typeof InscripcionesRoute
  InvitadosRoute: typeof InvitadosRoute
  ProgramaRoute: typeof ProgramaRoute
  SedeRoute: typeof SedeRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sede': {
      id: '/sede'
      path: '/sede'
      fullPath: '/sede'
      preLoaderRoute: typeof SedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa': {
      id: '/programa'
      path: '/programa'
      fullPath: '/programa'
      preLoaderRoute: typeof ProgramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitados': {
      id: '/invitados'
      path: '/invitados'
      fullPath: '/invitados'
      preLoaderRoute: typeof InvitadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscripciones': {
      id: '/inscripciones'
      path: '/inscripciones'
      fullPath: '/inscripciones'
      preLoaderRoute: typeof InscripcionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacion': {
      id: '/informacion'
      path: '/informacion'
      fullPath: '/informacion'
      preLoaderRoute: typeof InformacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenidos': {
      id: '/bienvenidos'
      path: '/bienvenidos'
      fullPath: '/bienvenidos'
      preLoaderRoute: typeof BienvenidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoridades': {
      id: '/autoridades'
      path: '/autoridades'
      fullPath: '/autoridades'
      preLoaderRoute: typeof AutoridadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alojamiento': {
      id: '/alojamiento'
      path: '/alojamiento'
      fullPath: '/alojamiento'
      preLoaderRoute: typeof AlojamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlojamientoRoute: AlojamientoRoute,
  AutoridadesRoute: AutoridadesRoute,
  BienvenidosRoute: BienvenidosRoute,
  InformacionRoute: InformacionRoute,
  InscripcionesRoute: InscripcionesRoute,
  InvitadosRoute: InvitadosRoute,
  ProgramaRoute: ProgramaRoute,
  SedeRoute: SedeRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
