/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as ProgramaRouteImport } from './routes/programa'
import { Route as InscripcionesRouteImport } from './routes/inscripciones'
import { Route as InformacionRouteImport } from './routes/informacion'
import { Route as AutoridadesRouteImport } from './routes/autoridades'
import { Route as AlojamientoRouteImport } from './routes/alojamiento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramaIndexRouteImport } from './routes/programa.index'
import { Route as ProgramaTecnicoRouteImport } from './routes/programa.tecnico'
import { Route as ProgramaSocietariasRouteImport } from './routes/programa.societarias'
import { Route as ProgramaSocialRouteImport } from './routes/programa.social'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaRoute = ProgramaRouteImport.update({
  id: '/programa',
  path: '/programa',
  getParentRoute: () => rootRouteImport,
} as any)
const InscripcionesRoute = InscripcionesRouteImport.update({
  id: '/inscripciones',
  path: '/inscripciones',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacionRoute = InformacionRouteImport.update({
  id: '/informacion',
  path: '/informacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoridadesRoute = AutoridadesRouteImport.update({
  id: '/autoridades',
  path: '/autoridades',
  getParentRoute: () => rootRouteImport,
} as any)
const AlojamientoRoute = AlojamientoRouteImport.update({
  id: '/alojamiento',
  path: '/alojamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaIndexRoute = ProgramaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramaRoute,
} as any)
const ProgramaTecnicoRoute = ProgramaTecnicoRouteImport.update({
  id: '/tecnico',
  path: '/tecnico',
  getParentRoute: () => ProgramaRoute,
} as any)
const ProgramaSocietariasRoute = ProgramaSocietariasRouteImport.update({
  id: '/societarias',
  path: '/societarias',
  getParentRoute: () => ProgramaRoute,
} as any)
const ProgramaSocialRoute = ProgramaSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => ProgramaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alojamiento': typeof AlojamientoRoute
  '/autoridades': typeof AutoridadesRoute
  '/informacion': typeof InformacionRoute
  '/inscripciones': typeof InscripcionesRoute
  '/programa': typeof ProgramaRouteWithChildren
  '/sponsors': typeof SponsorsRoute
  '/programa/social': typeof ProgramaSocialRoute
  '/programa/societarias': typeof ProgramaSocietariasRoute
  '/programa/tecnico': typeof ProgramaTecnicoRoute
  '/programa/': typeof ProgramaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alojamiento': typeof AlojamientoRoute
  '/autoridades': typeof AutoridadesRoute
  '/informacion': typeof InformacionRoute
  '/inscripciones': typeof InscripcionesRoute
  '/sponsors': typeof SponsorsRoute
  '/programa/social': typeof ProgramaSocialRoute
  '/programa/societarias': typeof ProgramaSocietariasRoute
  '/programa/tecnico': typeof ProgramaTecnicoRoute
  '/programa': typeof ProgramaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alojamiento': typeof AlojamientoRoute
  '/autoridades': typeof AutoridadesRoute
  '/informacion': typeof InformacionRoute
  '/inscripciones': typeof InscripcionesRoute
  '/programa': typeof ProgramaRouteWithChildren
  '/sponsors': typeof SponsorsRoute
  '/programa/social': typeof ProgramaSocialRoute
  '/programa/societarias': typeof ProgramaSocietariasRoute
  '/programa/tecnico': typeof ProgramaTecnicoRoute
  '/programa/': typeof ProgramaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alojamiento'
    | '/autoridades'
    | '/informacion'
    | '/inscripciones'
    | '/programa'
    | '/sponsors'
    | '/programa/social'
    | '/programa/societarias'
    | '/programa/tecnico'
    | '/programa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alojamiento'
    | '/autoridades'
    | '/informacion'
    | '/inscripciones'
    | '/sponsors'
    | '/programa/social'
    | '/programa/societarias'
    | '/programa/tecnico'
    | '/programa'
  id:
    | '__root__'
    | '/'
    | '/alojamiento'
    | '/autoridades'
    | '/informacion'
    | '/inscripciones'
    | '/programa'
    | '/sponsors'
    | '/programa/social'
    | '/programa/societarias'
    | '/programa/tecnico'
    | '/programa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlojamientoRoute: typeof AlojamientoRoute
  AutoridadesRoute: typeof AutoridadesRoute
  InformacionRoute: typeof InformacionRoute
  InscripcionesRoute: typeof InscripcionesRoute
  ProgramaRoute: typeof ProgramaRouteWithChildren
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa': {
      id: '/programa'
      path: '/programa'
      fullPath: '/programa'
      preLoaderRoute: typeof ProgramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscripciones': {
      id: '/inscripciones'
      path: '/inscripciones'
      fullPath: '/inscripciones'
      preLoaderRoute: typeof InscripcionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacion': {
      id: '/informacion'
      path: '/informacion'
      fullPath: '/informacion'
      preLoaderRoute: typeof InformacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoridades': {
      id: '/autoridades'
      path: '/autoridades'
      fullPath: '/autoridades'
      preLoaderRoute: typeof AutoridadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alojamiento': {
      id: '/alojamiento'
      path: '/alojamiento'
      fullPath: '/alojamiento'
      preLoaderRoute: typeof AlojamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa/': {
      id: '/programa/'
      path: '/'
      fullPath: '/programa/'
      preLoaderRoute: typeof ProgramaIndexRouteImport
      parentRoute: typeof ProgramaRoute
    }
    '/programa/tecnico': {
      id: '/programa/tecnico'
      path: '/tecnico'
      fullPath: '/programa/tecnico'
      preLoaderRoute: typeof ProgramaTecnicoRouteImport
      parentRoute: typeof ProgramaRoute
    }
    '/programa/societarias': {
      id: '/programa/societarias'
      path: '/societarias'
      fullPath: '/programa/societarias'
      preLoaderRoute: typeof ProgramaSocietariasRouteImport
      parentRoute: typeof ProgramaRoute
    }
    '/programa/social': {
      id: '/programa/social'
      path: '/social'
      fullPath: '/programa/social'
      preLoaderRoute: typeof ProgramaSocialRouteImport
      parentRoute: typeof ProgramaRoute
    }
  }
}

interface ProgramaRouteChildren {
  ProgramaSocialRoute: typeof ProgramaSocialRoute
  ProgramaSocietariasRoute: typeof ProgramaSocietariasRoute
  ProgramaTecnicoRoute: typeof ProgramaTecnicoRoute
  ProgramaIndexRoute: typeof ProgramaIndexRoute
}

const ProgramaRouteChildren: ProgramaRouteChildren = {
  ProgramaSocialRoute: ProgramaSocialRoute,
  ProgramaSocietariasRoute: ProgramaSocietariasRoute,
  ProgramaTecnicoRoute: ProgramaTecnicoRoute,
  ProgramaIndexRoute: ProgramaIndexRoute,
}

const ProgramaRouteWithChildren = ProgramaRoute._addFileChildren(
  ProgramaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlojamientoRoute: AlojamientoRoute,
  AutoridadesRoute: AutoridadesRoute,
  InformacionRoute: InformacionRoute,
  InscripcionesRoute: InscripcionesRoute,
  ProgramaRoute: ProgramaRouteWithChildren,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
